title: Notif.me Documentation
email: your-email@domain.com
description: "Simply the best way to notify your users"
baseurl: "/notifme-docs" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: notif_me
github_username:  notifme

# Build settings
markdown: kramdown
theme: jekyll-theme-architect
gems:
  - jekyll-feed
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
